var gulp = require('gulp');

/*---------  Sass ---------*/

var sass = require('gulp-sass');

gulp.task('sass', function(){
  return gulp.src('site/sass/**/*.scss')
    .pipe(sass()) 
    .pipe(gulp.dest('site/css'))
    .pipe(browserSync.reload({
      stream: true
    }))
});

gulp.task('watch', ['browserSync', 'sass'], function (){
	gulp.watch('site/sass/**/*.scss', ['sass']);
	gulp.watch('site/*.html', browserSync.reload); 
  	gulp.watch('site/js/**/*.js', browserSync.reload);  
});

/*--------- BrowserSync ---------*/

var browserSync = require('browser-sync').create();

gulp.task('browserSync', function() {
  browserSync.init({
    server: {
      baseDir: 'site'
    },
  })
})

/*--------- Concatenation and Minifying ---------*/

var useref = require('gulp-useref');
var uglify = require('gulp-uglify');
var gulpIf = require('gulp-if');
var cssnano = require('gulp-cssnano');

gulp.task('useref', function(cb){
  return gulp.src(['site/*.html'])
    .pipe(useref())
    .pipe(gulpIf('*.js', uglify()))
    .pipe(gulpIf('*.css', cssnano()))
    .pipe(gulp.dest('dist'))
});

/*--------- Check erors ---------*/

var pump = require('pump');

gulp.task('error', function (cb) {
  pump([
    gulp.src('site/**/*.js'),
    uglify(),
    gulp.dest('./dist/')
  ], cb);
});

/*--------- Optimizing images ---------*/

var imagemin = require('gulp-imagemin');
var cache = require('gulp-cache');

gulp.task('images', function(){
  return gulp.src('site/img/**/*.+(png|jpg|jpeg|gif|svg)')
  // Caching images that ran through imagemin
  .pipe(cache(imagemin({
      interlaced: true
    })))
  .pipe(gulp.dest('dist/img'))
});

//Clear cache
gulp.task('cache:clear', function (callback) {
return cache.clearAll(callback)
})

/*--------- Deleting autogenerated files ---------*/

var del = require('del');

gulp.task('clean:dist', function() {
  return del.sync('dist');
})

/*--------- Combining all tasks ---------*/

var runSequence = require('run-sequence');

gulp.task('build', function (callback) {
  runSequence('clean:dist', 
    ['sass', 'useref', 'images']
  )
})

gulp.task('default', function (callback) {
  runSequence(['sass','browserSync', 'watch']
  )
})